# Generated by Django 5.2.8 on 2025-12-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
