# Generated by Django 5.2.8 on 2025-12-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_clientes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
