# Generated by Django 6.0 on 2026-01-20 15:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_clientes_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='password',
        ),
        migrations.AddField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='clientes',
            name='documento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=10)),
                ('en_turno', models.BooleanField(default=False)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='app.rol')),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
