# Generated by Django 6.0 on 2026-01-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rol_remove_clientes_password_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Empleados',
        ),
        migrations.RenameModel(
            old_name='Rol',
            new_name='Roles',
        ),
    ]
