# Generated by Django 5.2.8 on 2026-01-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_categoria_categorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
