# Generated by Django 6.0 on 2026-01-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_clientes_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='en_turno',
        ),
        migrations.AddField(
            model_name='clientes',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.roles'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.roles'),
        ),
    ]
