# Generated by Django 4.2.27 on 2026-01-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_empleados_en_turno_clientes_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
