# Generated by Django 4.2.27 on 2026-01-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_empleados_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='email',
            new_name='correo',
        ),
    ]
